# Generated by Django 4.2.7 on 2025-11-13 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'journal_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.DecimalField(decimal_places=4, help_text='Score from -1 to 1', max_digits=5)),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=4, help_text='0 to 1', max_digits=5)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='journal.journalentry')),
            ],
            options={
                'verbose_name': 'Sentiment Analysis',
                'verbose_name_plural': 'Sentiment Analyses',
                'db_table': 'sentiment_analysis',
            },
        ),
        migrations.CreateModel(
            name='MoodSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='journal.journalentry')),
            ],
            options={
                'verbose_name': 'Mood Suggestion',
                'verbose_name_plural': 'Mood Suggestions',
                'db_table': 'mood_suggestions',
            },
        ),
    ]
