# Generated by Django 4.2.7 on 2026-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodsuggestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mood Suggestion', 'verbose_name_plural': 'Mood Suggestions'},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='ความมั่นใจในการวิเคราะห์', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=4, help_text='คะแนนอารมณ์ (-1.0 ถึง 1.0)', max_digits=5),
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table=None,
        ),
        migrations.AlterModelTable(
            name='moodsuggestion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sentimentanalysis',
            table=None,
        ),
    ]
